- platform: adcpi
  name: ADCPi
  i2c_address: 0x68
  i2c_address2: 0x69
  pga: 1
  bitrate: 18
  scan_interval: 5

- platform: template
  sensors:
    adcinput1:
      value_template: '{{states.sensor.adcpi.attributes.input1}}'
      friendly_name: 'ADC input 1'
      unit_of_measurement: 'Volts'
    adcinput2:
      value_template: '{{states.sensor.adcpi.attributes.input2}}'
      friendly_name: 'ADC input 2'
      unit_of_measurement: 'Volts'
    adcinput3:
      value_template: '{{states.sensor.adcpi.attributes.input3}}'
      friendly_name: 'ADC input 3'
      unit_of_measurement: 'Volts'
    adcinput4:
      value_template: '{{states.sensor.adcpi.attributes.input4}}'
      friendly_name: 'ADC input 4'
      unit_of_measurement: 'Volts'
    adcinput5:
      value_template: '{{states.sensor.adcpi.attributes.input5}}'
      friendly_name: 'ADC input 5'
      unit_of_measurement: 'Volts'
    adcinput6:
      value_template: '{{states.sensor.adcpi.attributes.input6}}'
      friendly_name: 'ADC input 6'
      unit_of_measurement: 'Volts'
    adcinput7:
      value_template: '{{states.sensor.adcpi.attributes.input7}}'
      friendly_name: 'ADC input 7'
      unit_of_measurement: 'Volts'
    adcinput8:
      value_template: '{{states.sensor.adcpi.attributes.input8}}'
      friendly_name: 'ADC input 8'
      unit_of_measurement: 'Volts'  